//es como una gestion de errores 

try {
    let x = 0
    throw(' Este es mi error')
} catch (error) {
    alert("lo sentimos, se ha producido un error" + error)//es como un if para errores 
}

